drop gulp, typings, old dependencies
akashic-games/akashic-tile pull request #4
Opened 2017-12-08 15:26 UTC by kamakiri01

## このpull requestが解決する内容

ビルドツールからgulp, typings, TypeScript1系を除きます。

## 破壊的な変更を含んでいるか?

- NO

2017-12-11 09:43 UTC, xnv requested changes

2017-12-11 09:43 UTC, xnv commented on package.json
> +	"rimraf": "^2.6.1",
インデント壊れています。

2017-12-11 09:43 UTC, xnv commented on sample/package.json
> +	"build": "npm run build:tsc && cd game && akashic update asset script -q",
こちらもインデント壊れです。

2017-12-11 09:43 UTC, xnv commented on tslint.json
> +    "variable-declaration": "nospace"
全体的にこれは意図したインデントなんでしょうか。

2017-12-11 09:43 UTC, xnv commented on tslint.json
> -    "no-duplicate-key": true,
このへん削除したのはどういうモチベーションなんでしょうか？

2017-12-11 09:43 UTC, xnv commented on tsconfig.json
> +	"noLib": false,
あまり厳密に調べていないのですが、 `noLib` はもはや不要なのではありませんか。 (lib つけてますし)

2017-12-11 09:43 UTC, xnv commented on sample/package.json
> +    "@akashic-extension/akashic-tile": "0.1.1",
この部分は publish 後に更新するという想定でよいでしょうか。

2017-12-11 09:43 UTC, xnv commented on spec/helpers/mock.ts
> -		this.game = game;
細かい上にこの場所では大して重要な話でもありませんが、原則コンストラクタでは全メンバ初期化したいです。 `null` 入れておきませんか。

2017-12-11 11:33 UTC, kamakiri01 commented on tsconfig.json
> +	"noLib": false,
default: falseなので無くて良さそうです。
https://www.typescriptlang.org/docs/handbook/compiler-options.html

2017-12-11 11:36 UTC, kamakiri01 commented on tslint.json
> +    "variable-declaration": "nospace"
全体的に直します。

2017-12-11 11:37 UTC, kamakiri01 commented on spec/helpers/mock.ts
> -		this.game = game;
akashic-label と共通で使っているので両方直します。

2017-12-11 11:37 UTC, kamakiri01 commented on sample/package.json
> +	"build": "npm run build:tsc && cd game && akashic update asset script -q",
直します。

2017-12-11 11:37 UTC, kamakiri01 commented on package.json
> +	"rimraf": "^2.6.1",
こちらも直します。

2017-12-11 11:38 UTC, kamakiri01 commented on tslint.json
> -    "no-duplicate-key": true,
ベースにした tslint.json の間違いですね…直します。

2017-12-12 01:36 UTC, yu-ogi commented on package.json
> +    "devDependencies": {
このあたりまだインデントが崩れているようです。

2017-12-12 03:43 UTC, kamakiri01 commented on package.json
> +    "devDependencies": {
うっ。直します。

2017-12-12 08:37 UTC, yu-ogi approved these changes

2017-12-13 05:47 UTC, xnv approved these changes

2017-12-14 05:44 UTC, merged